### ISSUE TITLE
 Open gov 가이드라인 작업 시작 (7.14 논의내용) 

### ISSUE THREAD

**Issue by jenniferkang** [codenamu/opengov-guideline#1]
@mozodev 님과 오늘  논의한 사항입니다. 
- 직접 활용을 하는 이용자 입장에서 공공데이터 개방을 위해서 꼭 지켜야 하는 지침서 (가이드라인)을 잡아보자 
- 너무 복잡하지 않게  최소한의 지켜야 하는 부분 / 이왕이면 지켰으면 하는 부분으로 나눠서 작업을 해보자 
- 해외 자료부터 먼저 찬찬히 찾아보자 
- 1차 지침을 만든 후에 핵심이 되는 데이터 5개를 잡아서 문제점이 없는지 검수해 보면서 잘된 예 / 잘못된 예를 찬찬히 정리해 보자 

우선 @mozodev 님에서 해외 자료를 검토해서 러프하게 지침 항목을 정리해 보기로 했습니다. 
(가능한 일정을 알려주세요)

**Comment by mozodev** [comment]
@jenniferkang 이번주는 공유허브 마무리해야 하는 일들이 많아서 도저히 안되겠습니다. 다음 주 화요일에는 정리한 문서를 보고 다시 이야기할 수 있겠습니다.
